trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- script: ls 
  displayName: 'List all the files'

- script: |
    cp databricks-config ~/.databrickscfg
    databricks workspace ls
  displayName: 'Copy the file'
