# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'reg-dev-eu-modelservingplatform (SPN)'
    scriptType: 'batch'
    scriptLocation: 'inlineScript'
    inlineScript: 'az storage account create --resource-group exampleGroup --name examplestore --location westus --sku Standard_LRS --kind StorageV2'